{
    'name' : 'Cash on Delivery',
    'version' : '1.0',
    'summary': 'Cash on Delivery Payment Method',
    'description': 'Module to add Cash on Delivery as a payment method in Odoo',
    'category': 'Accounting',
    'depends' : ['payment', 'sale', 'account', 'website', 'website_sale', 'payment', 'product'],
    'data': [
        'data/cod_fee_product.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
        'views/website_cod_product.xml',
        'security/ir.model.access.csv',
        'views/payment_provider_views.xml',
        'views/cod_config_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}